name: Sample Workflow

on:
  push:
    branches:
      - main   # or "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List project files
        run: ls -R

      - name: Validate HTML file exists
        run: |
          if [ ! -f index.html ]; then
            echo "❌ index.html not found!"
            exit 1
          else
            echo "✅ index.html found!"
          fi
